package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new com.adivery.plugin.AdiveryPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin adivery, com.adivery.plugin.AdiveryPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.animated_rating_stars.AnimatedRatingStarsPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin animated_rating_stars, com.example.animated_rating_stars.AnimatedRatingStarsPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin path_provider_android, io.flutter.plugins.pathprovider.PathProviderPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.rhyme.r_get_ip.RGetIpPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin r_get_ip, com.rhyme.r_get_ip.RGetIpPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin sqflite, com.tekartik.sqflite.SqflitePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.urllauncher.UrlLauncherPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin url_launcher_android, io.flutter.plugins.urllauncher.UrlLauncherPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new billion.group.wireguard_flutter.WireguardFlutterPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin wireguard_flutter, billion.group.wireguard_flutter.WireguardFlutterPlugin", e);
    }
  }
}
